---

- hosts: demo[0]
  become: yes
  
  tasks:
  
    - name: remove old images
      command: docker system prune -a -f
      
    - name: create docker image using war file
      command: docker build -t devopsnike/project:latest .
      args:
        chdir: /home/ansible/123

    - name: push image on to dockerhub
      command: docker push devopsnike/project:latest
