---

- hosts: demo[1]
  become: true
  
  tasks:
    - name: stop previous containers
      command: docker stop $(docker ps -aq)
      
    - name: remove previous containers
      command: docker rm $(docker ps -aq)
      
    - name: remove images
      command: docker system prune -a -f
      
    - name: pull & start the container
      command: docker run -d --name project -p 8080:8080 devopsnike/project:latest
